@echo off
set proxycap_file=C:/Users/WDAGUtilityAccount/Desktop/files/pcap536_x64.msi
echo Extracting Proxycap registration key...
echo please wait ...
"%proxycap_file%" /qn /norestart
:: get Registration Key
"reg" "export" "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Proxy Labs\ProxyCap\Registration" "C:/Users/WDAGUtilityAccount/Desktop/files/Registration.reg" /Y
echo [DONE] Extracting Proxycap registration key...
echo Sandbox closing...
TIMEOUT /T 10 >nul
